export const PROGRESS_CHANGED = 'PROGRESS_CHANGED'
export const DOWNLOAD_FINISHED = 'DONWLOAD_FINISHED'
export const INSTALL_STARTED = 'INSTALL_STARTED'
export const INSTALL_FINISHED = 'INSTALL_FINISHED'

